Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.synced_folder "../userapi", "/home/vagrant/userapi"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/main.yml"
  end
end
