Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.synced_folder "../userapi", "/home/vagrant/userapi"

  # Use ansible_local to run Ansible inside the guest (better for Windows hosts)
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/main.yml"
    ansible.install = true # Install Ansible in the guest automatically
  end
end
